### ISSUE TITLE
Flyway improvement

### ISSUE THREAD

**Issue by mrclrchtr** [raphiz/database-build-integration#1]
Hi, I saw your commit in this issue: https://github.com/flyway/flyway/issues/3550

And I wanted to say thank you! I just copied your code.

I improved it a little bit, to make it more cacheable and wanted to let you know:

```kotlin
@CacheableTask
abstract class FlywayMigrateTask : DefaultTask() {

  @get:Input
  abstract val driver: Property<String>

  @get:Input
  abstract val url: Property<String>

  @get:Input
  abstract val username: Property<String>

  @get:Input
  abstract val password: Property<String>

  @get:Input
  abstract val schemas: Property<String>

  @get:InputDirectory
  @get:PathSensitive(PathSensitivity.RELATIVE)
  abstract var migrationsLocation: Directory

  // Output is required to make the task cacheable
  @OutputFile
  val outputFile: RegularFileProperty = project.objects.fileProperty().convention(
    project.layout.buildDirectory.file("flyway/migration.marker")
  )

  @TaskAction
  fun run() {
    Flyway.configure()
      .driver(driver.get())
      .dataSource(url.get(), username.get(), password.get())
      .schemas(schemas.get())
      .locations("filesystem:${migrationsLocation.asFile}")
      .cleanOnValidationError(true)
      .load()
      .migrate()

    // Create a marker file to indicate the task has executed successfully
    outputFile.get().asFile.writeText("Flyway migration completed")
  }
}
```

Result:
Task :service:flywayMigrate UP-TO-DATE  🥳

**Comment by raphiz** [comment]
Hey, thank you! I really appreciate you taking the time to submit this improvement!

I've also considered this approach with the fake output, but I believe it's not without issues. From Gradle's perspective, everything appears fine as long as the output file exists. Since the task is cacheable, there's nothing preventing Gradle from skipping task execution and simply retrieving the cached file with its basic contents, bypassing the migration entirely. The only situation where this is acceptable is when the output itself is the database, as is the case with SQLite for example (for which I actually implemented this pattern in another project).

In my experience, running Flyway all the time isn't typically the performance bottleneck - it's usually quite fast. I would recommend optimizing the database setup first (as done in this Repository) or - if performance is still a concern - only running the `flywayMigrate` task the first time for every Gradle daemon. This ensures that the task still runs frequently and if an issue occurs (for example the db container is recreated) one can simply stop all daemons and run the build again.

```kotlin
package io.github.raphiz.dbbuild

import org.flywaydb.core.Flyway
import org.gradle.api.DefaultTask
import org.gradle.api.file.Directory
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputDirectory
import org.gradle.api.tasks.TaskAction

abstract class FlywayMigrateTask : DefaultTask() {

    @get:Input
    abstract val url: Property<String>

    @get:Input
    abstract val username: Property<String>

    @get:Input
    abstract val password: Property<String>

    @get:InputDirectory
    abstract var migrationsLocation: Directory

    init {
        this.onlyIf { DaemonState.isFirstRunOnDaemon }
    }

    @TaskAction
    fun run() {
        Flyway.configure()
            .dataSource(url.get(), username.get(), password.get())
            .locations("filesystem:${migrationsLocation.asFile}")
            .cleanOnValidationError(true)
            .load()
            .migrate()
        DaemonState.isFirstRunOnDaemon = false

    }
}

object DaemonState {
    var isFirstRunOnDaemon: Boolean = true
}
```

Hope this helps :)

**Comment by mrclrchtr** [comment]
Hi, thanks for the answer! 

I think it all depends on what you want to achieve with the task. You are right if it is important that the database should really “always” be updated. 

In my case, the database only serves as a source for the Jooq code generator during the build. Both only need to be executed when the migration scripts change. And that happens in definitely.

The problem if the Taks is not completely cachable is that follow up tasks are also no longer cachable. In my case, this means that Jooq codegen is executed in any case.

Translated with DeepL.com (free version)

**Comment by mrclrchtr** [comment]
Hi, thanks for the answer! 

I think it all depends on what you want to achieve with the task. You are right if it is important that the database should really “always” be updated. 

In my case, the database only serves as a source for the Jooq code generator during the build. Both only need to be executed when the migration scripts change. And that happens in definitely.

The problem if the Taks is not completely cachable is that follow up tasks are also no longer cachable. In my case, this means that Jooq codegen is executed in any case.

**Comment by raphiz** [comment]
Fair point. If you only need it for jOOQ, i guess that's fine. Since I use it also to prepare the database schema for the database integration tests, I just configured the [jOOQ Code Gen task to consider the migrations as input](https://github.com/raphiz/database-build-integration/blob/main/buildSrc/src/main/kotlin/io/github/raphiz/dbbuild/database.gradle.kts#L53), which still makes it cacheable even if the `flywayMigrate` is executed. 
```
➜ ./gradlew test
Reusing configuration cache.
> Task :checkKotlinGradlePluginConfigurationErrors SKIPPED
> Task :processTestResources NO-SOURCE
> Task :processResources UP-TO-DATE
> Task :flywayMigrate
> Task :jooqCodegen UP-TO-DATE
> Task :compileKotlin UP-TO-DATE
> Task :compileJava NO-SOURCE
...
```

**Comment by mrclrchtr** [comment]
That is also a possibility. But in principle, the app should always carry out the migrations, right? That also makes sense in the test case, because you test the migration at the same time. 

In addition, “isFirstRunOnDaemon” does not ensure that the migration has really run in the DB. If you delete the DB manually after the first run, the task would definitely have to be executed again, which is difficult without restarting the daemon.
If the app always tests the migration at startup, this happens automatically.

But these are now very theoretical cases ;) Both are good solutions. Thank you very much for the code.

**Comment by raphiz** [comment]
Agreed, I should have mentioned that my assumptions were focused around the idea of having lots of database integration tests :smiley:  Thanks again!
